# Generated by Django 3.1.5 on 2021-03-22 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210317_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 14, 9, 19, 755014, tzinfo=utc)),
        ),
    ]
