# Generated by Django 3.1.5 on 2021-03-22 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210322_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expired',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 14, 19, 11, 710624, tzinfo=utc)),
        ),
    ]
